version: '3'
services:
 
  #PHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mi-app-laravel
    container_name: app_prueba
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app_prueba
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
        - ./:/var/www
        - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
 
  #Nginx
  webserver:
    image: nginx:alpine
    container_name: webserver_prueba
    restart: unless-stopped
    tty: true
    ports:
      - "8085:80"
      - "445:443"
    volumes:
        - ./:/var/www
        - ./nginx/conf.d:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
 
  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db_prueba
    restart: unless-stopped
    tty: true
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: prueba
      MYSQL_ROOT_PASSWORD: prueba
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
        - /docker-volumes/prueba:/var/lib/mysql
        - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
 
#Redes
networks:
  app-network:
    driver: bridge